#include "canvas_event.h"

DEFINE_EVENT_TYPE(wxEVT_CANVAS_ZOOM_CHANGED)
DEFINE_EVENT_TYPE(wxEVT_CANVAS_ZOOM_IN)
DEFINE_EVENT_TYPE(wxEVT_CANVAS_ZOOM_OUT)

IMPLEMENT_DYNAMIC_CLASS(wxCanvasEvent, wxNotifyEvent)
